name: resource_provider
description: A simple container for getting resources and creating them if required.
version: 1.0.0
# homepage: https://www.example.com

environment:
  sdk: '>=2.12.0 <3.0.0'

dependencies:
  meta: ^1.7.0
  quiver: ^3.1.0

dev_dependencies:
  lints: ^2.0.0
  test: ^1.16.0
